# Site settings
title: OOOTOKO
description: Life is originally hard.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://oootoko.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daenam Kim
user_description: Life is originally hard.
twitter_username: DaenamKim
github_username: daenamkim
disqus_username: oootoko-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Series
    url: /series
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
