# Site settings
title: OOOTOKO
description: Be a better person!
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://oootoko.net" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daenam Kim
user_description: Be a better person!
email: daenam.kim@gmail.com
twitter_username: DaenamKim
github_username: daenamkim
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  # - title: Series
  #   url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
